"""
Django settings for ip2pdirect project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from infuraeth import infura_settings
from django.utils.translation import ugettext_lazy as _
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's$#nb%8vr^l6wlrmzdzj$aovtyj==5k5#fz6$vj$$w-o+%8k(_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['ip2pgo.com', 'www.ip2pgo.com', 'my.ip2pgo.com', 'id.ip2pgo.com', 'au.ip2pgo.com', 'vn.ip2pgo.com', 'ng.ip2pgo.com', 'gh.ip2pgo.com', 'za.ip2pgo.com', 'tz.ip2pgo.com', 'otc.ip2pgo.com', 'bw.ip2pgo.com', 'ph.ip2pgo.com', 'rico.ip2pgo.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'directapp.apps.DirectappConfig',
    'infuraeth.apps.InfuraethConfig',
    'ip2pwebsite.apps.Ip2PwebsiteConfig',
    'promotions.apps.PromotionsConfig',
    'dispute.apps.DisputeConfig',
    'rico',
    'ip2padmin',
    'widget_tweaks',
    'solc',
    'web3',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'ip2pwebsite.middleware.slash_middleware.AppendOrRemoveSlashMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

SESSION_EXPIRE = 86400 #24 hours

#SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True #Default expire

ROOT_URLCONF = 'ip2pdirect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ip2pdirect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ip2pgo',
        'USER': 'dbmasteruser',
        'PASSWORD': 'D1lig3nt2oiB',
        'HOST': 'ls-9e60f499f8f52df42e9267f2a6375abd9501e4cd.cjwfcplqnbeg.ap-southeast-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#email handing
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_USE_TLS = True
#EMAIL_HOST = 'smtp.sendgrid.net'
#EMAIL_HOST_USER = 'iP2PGO'
#EMAIL_HOST_PASSWORD = 'Diligent_2018'
#EMAIL_PORT = 587
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ip2pglobal@gmail.com'
#EMAIL_HOST_USER = 'admin@ip2pgo.com'
EMAIL_HOST_PASSWORD = 'Diligent_2018'
#EMAIL_HOST_USER = 'ip2pgo.email@gmail.com'
#EMAIL_HOST_PASSWORD = 'Diligent2018'
#EMAIL_HOST = 'mail.ip2pmoney.com'
#EMAIL_HOST_USER = 'admin@ip2pmoney.com'
#EMAIL_HOST_PASSWORD = 'ip2p@dmin'
#EMAIL_HOST = 'smtp.qq.com'
#EMAIL_HOST_USER = '3506129340@qq.com'
#EMAIL_HOST_PASSWORD = 'Onecity_9999'
EMAIL_PORT = 587
#EMAIL_HOST = 'mail.ip2pmoney.com'
#EMAIL_HOST_USER = 'admin@ip2pmoney.com'
#EMAIL_HOST_PASSWORD = 'ip2p@dmin'
#EMAIL_PORT = 587
#EMAIL_HOST = 'smtp.mail.yahoo.com'
#EMAIL_HOST_USER = 'ip2pgo@yahoo.com'
#EMAIL_HOST_PASSWORD = 'Diligent_2018'
#EMAIL_HOST = 'smtp.qq.com'
#EMAIL_HOST_USER = '3506129340@qq.com'
#EMAIL_HOST_PASSWORD = 'Onecity_9999'
#EMAIL_PORT = 587

#pusher



# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/
LANGUAGES = (
    ('en-us', _('English')),
    ('id', _('Indonesian')),
    ('zh-hans', _('Simplified Chinese')),
    ('vi', _('Vietnamese')),
)


LANGUAGE_CODE ='en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '../directapp/static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

INFURA_API_KEY = infura_settings.API_KEY
INFURA_ETH_KEY = infura_settings.PRIVATE_KEY
ETHERSCAN_KEY = infura_settings.ETHERSCAN_KEY
DEPOSIT = infura_settings.DEPOSIT
WITHDRAW = infura_settings.WITHDRAW
os.environ['INFURA_API_KEY'] = INFURA_API_KEY
MAIN_WALLET = '0x1F20EE7Ac5A6d2e6c01a89C6C5D6161840160020'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi-redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('localhost', 6379)],
        },
        'ROUTING': 'ip2pdirect.routing.channel_routing',
    }
}


#if os.environ.get('DJANGO_DEV', 'true'):
#    from ip2pdirect.dev_settings import *

